#cloud-config
timezone: Asia/Singapore
package_update: true
package_upgrade: true

packages:
  - curl
  - iptables-persistent

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "journald"
      }

runcmd:
  # Configure iptables
  - [iptables, -I, INPUT, "1", -p, tcp, --dport, "80", -j, ACCEPT]
  - [iptables, -I, INPUT, "1", -p, tcp, --dport, "443", -j, ACCEPT]
  - [iptables, -I, INPUT, "1", -p, udp, --dport, "443", -j, ACCEPT]
  - [iptables, -I, INPUT, "1", -p, tcp, --dport, "3000", -j, ACCEPT]
  - [netfilter-persistent, save]

  # Install Docker
  - [curl, -fsSL, "https://get.docker.com", -o, /tmp/get-docker.sh]
  - [sh, /tmp/get-docker.sh]
  - [usermod, -aG, docker, ubuntu]
  - [rm, /tmp/get-docker.sh]

power_state:
  mode: reboot
  message: Rebooting after cloud-init setup
  condition: true
