#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - curl
  - git
  - iptables-persistent
  - unattended-upgrades

write_files:
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

runcmd:
  # Configure iptables
  - [iptables, -I, INPUT, 1, -p, tcp, --dport, 80, -j, ACCEPT]
  - [iptables, -I, INPUT, 1, -p, tcp, --dport, 443, -j, ACCEPT]
  - [iptables, -I, INPUT, 1, -p, udp, --dport, 443, -j, ACCEPT]
  - [iptables, -I, INPUT, 1, -p, tcp, --dport, 9443, -j, ACCEPT]
  - [sh, -c, "netfilter-persistent save"]

  # Install Docker
  - [curl, -fsSL, https://get.docker.com, -o, get-docker.sh]
  - [sh, get-docker.sh]
  - [usermod, -aG, docker, ubuntu]
  - [rm, get-docker.sh]

power_state:
  mode: reboot
  message: Rebooting after cloud-init setup
  condition: true
