- name: Preseed iptables-persistent answers
  ansible.builtin.debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: iptables-persistent/autosave_v4, value: "true" }
    - { question: iptables-persistent/autosave_v6, value: "true" }

- name: Install iptables-persistent
  ansible.builtin.package:
    name: iptables-persistent
    state: present

- name: Allow TCP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ oci_firewall_tcp_ports }}"

- name: Allow UDP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ oci_firewall_udp_ports }}"

- name: Save iptables rules
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: saved
