- name: Pre-seed debconf for iptables-persistent
  ansible.builtin.debconf:
    name: iptables-persistent
    question: "{{ item }}"
    vtype: boolean
    value: "true"
  loop:
    - iptables-persistent/autosave_v4
    - iptables-persistent/autosave_v6

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Allow TCP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ oci_firewall_tcp_ports }}"

- name: Allow UDP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ oci_firewall_udp_ports }}"

- name: Save iptables rules
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: saved
