version: 2
updates:
  - package-ecosystem: docker-compose
    directory: /portainer
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker-compose)"
    groups:
      docker-compose:
        patterns: ["*"]

  - package-ecosystem: docker-compose
    directory: /public
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker-compose)"
    groups:
      docker-compose:
        patterns: ["*"]

  - package-ecosystem: docker-compose
    directory: /usenet
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker-compose)"
    groups:
      docker-compose:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci(github-actions)
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: terraform
    directory: /oci-rm
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(terraform)"
    groups:
      terraform:
        patterns: ["*"]
