version: 2
updates:
  - package-ecosystem: docker
    directory: /portainer
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker)"
    groups:
      docker:
        applies-to: version-updates

  - package-ecosystem: docker
    directory: /public
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker)"
    groups:
      docker:
        applies-to: version-updates

  - package-ecosystem: docker
    directory: /usenet
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docker)"
    groups:
      docker:
        applies-to: version-updates

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci(github-actions)
    groups:
      github-actions:
        applies-to: version-updates

  - package-ecosystem: terraform
    directory: /oci-rm
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(terraform)"
