version: 2
updates:
  - package-ecosystem: docker-compose
    directories:
      - "/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(docker-compose)
    groups:
      docker-compose:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci(github-actions)
    groups:
      github-actions:
        update-types: [minor, patch]

  - package-ecosystem: terraform
    directory: /oci-rm
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(terraform)
    groups:
      terraform:
        update-types: [minor, patch]
