services:
  adguard:
    image: adguard/adguardhome:latest
    # cap_add:
    #   - NET_ADMIN # dhcp
    volumes:
      - /apps/adguard/conf:/opt/adguardhome/conf
      - /apps/adguard/work:/opt/adguardhome/work

    ports:
      # web service
      # - "80:80/tcp"
      - "3000:3000/tcp"

      # dns
      - target: 53
        published: 53
        protocol: tcp
        mode: host # for client ip addresses to show up correctly
      - target: 53
        published: 53
        protocol: udp
        mode: host # for client ip addresses to show up correctly

    # dns over https
    # - target: 443
    #   published: 443
    #   protocol: tcp
    #   mode: host

    # dns over tls
    # - target: 853
    #   published: 853
    #   protocol: tcp
    #   mode: host

    # dns over quic
    # - target: 853
    #   published: 853
    #   protocol: udp
    #   mode: host

    # dnscrypt
    # - target: 5443
    #   published: 5443
    #   protocol: tcp
    #   mode: host
    # - target: 5443
    #   published: 5443
    #   protocol: udp
    #   mode: host

    # dhcp
    # - 67:67/udp
    # - 68:68/tcp
    # - 68:68/udp
    healthcheck:
      test: ["CMD", "nslookup", "localhost", "localhost"]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy adguard adguard:3000
      caddy.@adguard_doh.host: "adguard.{env.DOMAIN}"
      caddy.@adguard_doh.path: /dns-query /dns-query/*
      caddy.handle: "@adguard_doh"
      caddy.handle.reverse_proxy: "adguard:443"
      caddy.handle.reverse_proxy.transport: http
      caddy.handle.reverse_proxy.transport.tls_server_name: "{host}"

networks:
  default:
    name: caddy
    external: true
