services:
  socket-proxy:
    # nosemgrep
    image: ghcr.io/linuxserver/socket-proxy:3.4.3@sha256:5253050dd304d351df2ee61bba43c57dd2b19bb640497a679592051de3a3c639
    environment:
      POST: 0

      # containers
      CONTAINERS: 1
      EXEC: 0
      # post only
      ALLOW_START: 1 # dozzle
      ALLOW_STOP: 1 # dozzle
      ALLOW_RESTARTS: 1 # autoheal

      # images
      IMAGES: 0
      # post only
      BUILD: 0
      COMMIT: 0

      # networks / volumes / plugins
      NETWORKS: 1 # caddy
      VOLUMES: 0
      PLUGINS: 0

      # swarm
      CONFIGS: 0 # caddy
      NODES: 0
      SECRETS: 0
      SERVICES: 0 # caddy
      SWARM: 0
      TASKS: 0

      # system
      # get only
      DISTRIBUTION: 0
      EVENTS: 1
      INFO: 1 # caddy
      PING: 1
      SYSTEM: 0
      VERSION: 1
      # post only
      AUTH: 0
      SESSION: 0
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    ports:
      - 127.0.0.1:2375:2375
    networks:
      - socket-proxy
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:2375/_ping"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  tailscale:
    # nosemgrep
    image: ghcr.io/tailscale/tailscale:v1.98.10@sha256:cdf5612ded5be1344f1a704b8c5e53496db97376bb533e5e15f141e48bf60cc0
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?}
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: ${TS_USERSPACE:-true}
      TS_ROUTES: ${TS_ROUTES:-}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_ENABLE_HEALTH_CHECK: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    read_only: true
    uts: host
    volumes:
      - /apps/tailscale:/var/lib/tailscale
    tmpfs:
      - /run
      - /tmp
    healthcheck:
      test: [CMD, wget, -nv, -O-, "http://localhost:9002/healthz"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:v8.0.0@sha256:51e70dd6f16cd3e4d845ac02d09940b10772a75b9d741427d235a78570923c1d
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID:?}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY:?}
      GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS:-GeoLite2-ASN GeoLite2-City GeoLite2-Country}
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY:-24}
    volumes:
      - /apps/geoip:/usr/share/GeoIP
    tmpfs:
      - /tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  whoami:
    # nosemgrep
    image: ghcr.io/traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    expose:
      - 80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth whoami whoami:80

  librespeed:
    # nosemgrep
    image: ghcr.io/librespeed/speedtest:6.2.0@sha256:199ddbb3543f7f988e99c9c3a7c4d31c1683d2adbba9597557ca4770082368ae
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    expose:
      - 8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth librespeed librespeed:8080

networks:
  default:
    name: proxy
    external: true
  socket-proxy:
    name: socket-proxy
