services:
  socket_proxy:
    # nosemgrep
    image: ghcr.io/linuxserver/socket-proxy:3.4.2@sha256:a9de14c1c9697de5384a63c2a8e1fdbb823d74f03c94cde77c59e149169c0326
    environment:
      TZ: ${TZ:-UTC}
      POST: 0

      # containers
      CONTAINERS: 1
      EXEC: 0
      # post only
      ALLOW_START: 1 # dozzle
      ALLOW_STOP: 1 # dozzle
      ALLOW_RESTARTS: 1 # autoheal

      # images
      IMAGES: 0
      # post only
      BUILD: 0
      COMMIT: 0

      # networks / volumes / plugins
      NETWORKS: 1 # caddy
      VOLUMES: 0
      PLUGINS: 0

      # swarm
      CONFIGS: 1 # caddy
      NODES: 0
      SECRETS: 0
      SERVICES: 1 # caddy
      SWARM: 0
      TASKS: 0

      # system
      # get only
      DISTRIBUTION: 0
      EVENTS: 1
      INFO: 1 # caddy
      PING: 1
      SYSTEM: 0
      VERSION: 1
      # post only
      AUTH: 0
      SESSION: 0
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    expose:
      - 2375
    networks:
      - socket_proxy
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:2375/_ping"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  tailscale:
    # nosemgrep
    image: ghcr.io/tailscale/tailscale:v1.98.8@sha256:d54b2e6a9c09f0e5ec52e82b9ad4af3d446b54a7c08075e92f11c39dd410105f
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?}
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TS_ROUTES:-}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_ENABLE_HEALTH_CHECK: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    uts: host
    volumes:
      - /apps/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    tmpfs:
      - /run
      - /tmp
    healthcheck:
      test: [CMD, wget, -nv, -O-, "http://localhost:9002/healthz"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  whoami:
    # nosemgrep
    image: ghcr.io/traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    expose:
      - 80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth whoami whoami:80

  librespeed:
    # nosemgrep
    image: ghcr.io/librespeed/speedtest:6.1.0@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    expose:
      - 8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth librespeed librespeed:8080

networks:
  default:
    name: proxy
    external: true
  socket_proxy:
    name: socket_proxy
