services:
  caddy:
    # nosemgrep
    image: ghcr.io/serfriz/caddy-duckdns-ddns-crowdsec-geoip-security-dockerproxy:2.11.4@sha256:d2486aeb3524ceb8412910c86f2f3e5f42fff2cbbfb9857f935a4006326e50b7
    container_name: caddy
    working_dir: /etc/caddy
    depends_on:
      socket_proxy:
        condition: service_healthy
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile
      CADDY_DOCKER_EVENT_THROTTLE_INTERVAL: 2s # for crowdset stream mode
      CROWDSEC_API_KEY: ${CROWDSEC_CADDY_BOUNCER_KEY:-}
      DOCKER_HOST: tcp://socket_proxy:2375
      DOMAIN: ${DOMAIN:?}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN:?}
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./caddy:/etc/caddy:ro
      - /apps/caddy:/config
      - /apps/caddy:/data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - default
      - socket_proxy
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: [CMD, wget, --spider, "http://127.0.0.1:2019/config/"]
    restart: unless-stopped

  tinyauth:
    # nosemgrep
    image: ghcr.io/tinyauthapp/tinyauth:v5.0.7@sha256:0793c71c49906e079d90c7e693cded9df569217a92d717dc9b171f2116fcd1c6
    depends_on:
      socket_proxy:
        condition: service_healthy
    environment:
      DOCKER_HOST: tcp://socket_proxy:2375
      TINYAUTH_APPURL: https://tinyauth.${DOMAIN:?}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ${TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET:-}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET: ${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET:-}
      TINYAUTH_OAUTH_WHITELIST: ${TINYAUTH_OAUTH_WHITELIST:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/tinyauth:/data
    expose:
      - 3000
    networks:
      - default
      - socket_proxy
    restart: unless-stopped
    labels:
      caddy: "*.$${DOMAIN}"
      caddy.import: reverse_proxy tinyauth tinyauth:3000

  socket_proxy:
    # nosemgrep
    image: ghcr.io/linuxserver/socket-proxy:3.4.0@sha256:cb30b9c279443b461666dba087975e8efe0ad7af03b7c81c053cdcff9aacd531
    environment:
      TZ: ${TZ:-UTC}
      POST: 0

      # containers
      CONTAINERS: 1
      EXEC: 0
      # post only
      ALLOW_START: 1 # dozzle
      ALLOW_STOP: 1 # dozzle
      ALLOW_RESTARTS: 1 # autoheal

      # images
      IMAGES: 0
      # post only
      BUILD: 0
      COMMIT: 0

      # networks / volumes / plugins
      NETWORKS: 1 # caddy
      VOLUMES: 0
      PLUGINS: 0

      # swarm
      CONFIGS: 1 # caddy
      NODES: 0
      SECRETS: 0
      SERVICES: 1 # caddy
      SWARM: 0
      TASKS: 0

      # system
      # get only
      DISTRIBUTION: 0
      EVENTS: 1
      INFO: 1 # caddy
      PING: 1
      SYSTEM: 0
      VERSION: 1
      # post only
      AUTH: 0
      SESSION: 0
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    expose:
      - 2375
    networks:
      - socket_proxy
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:2375/_ping"]
    restart: unless-stopped

  tailscale:
    # nosemgrep
    image: ghcr.io/tailscale/tailscale:v1.98.4@sha256:25cde9ad76020b0e29229136d0c38b5962e9a0e1774ffac9b0df68e4a37d6cf0
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?}
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TS_ROUTES:-}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_ENABLE_HEALTH_CHECK: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    uts: host
    volumes:
      - /apps/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    tmpfs:
      - /run
      - /tmp
    healthcheck:
      test: [CMD, wget, -nv, -O-, "http://localhost:9002/healthz"]
    restart: unless-stopped

  whoami:
    # nosemgrep
    image: ghcr.io/traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    expose:
      - 80
    restart: unless-stopped
    labels:
      caddy: "*.$${DOMAIN}"
      caddy.import: reverse_proxy_auth whoami whoami:80

  librespeed:
    # nosemgrep
    image: ghcr.io/librespeed/speedtest:6.1.0@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    expose:
      - 8080
    restart: unless-stopped
    labels:
      caddy: "*.$${DOMAIN}"
      caddy.import: reverse_proxy_auth librespeed librespeed:8080

networks:
  default:
    name: caddy
  socket_proxy:
    name: socket_proxy
