services:
  resticprofile:
    image: creativeprojects/resticprofile:0.29.0
    entrypoint: [sh]
    command: >-
      -c "resticprofile schedule --all && crond -f -L /dev/stdout"
    environment:
      RESTIC_PASSWORD_FILE: /run/secrets/restic_password
      RCLONE_CONFIG_GDRIVE_TYPE: drive
      RCLONE_CONFIG_GDRIVE_SCOPE: drive
      RCLONE_CONFIG_GDRIVE_CLIENT_ID: ${GDRIVE_CLIENT_ID:?}
      RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: ${GDRIVE_CLIENT_SECRET:?}
      RCLONE_CONFIG_GDRIVE_TOKEN: ${GDRIVE_TOKEN:?}
      RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID: ${GDRIVE_FOLDER_ID:?}
    secrets:
      - gdrive_service_account
      - restic_password
    volumes:
      - ./resticprofile:/resticprofile:ro
      - /apps:/apps:ro
      - /apps/resticprofile/cache:/var/cache/restic
    uts: host
    healthcheck:
      test: [CMD, resticprofile, --dry-run, backup]
    restart: unless-stopped

secrets:
  restic_password:
    environment: RESTIC_PASSWORD
