services:
  autorestic:
    image: cupcakearmy/autorestic:2.1.3
    entrypoint: [sh, -c]
    command:
      - |
        autorestic install && exec crond -f -l 2
    environment:
      AUTORESTIC_CONFIG: /config/.autorestic.yml
      AUTORESTIC_GDRIVE_RESTIC_PASSWORD: ${RESTIC_PASSWORD:?}
      RCLONE_CONFIG_GDRIVE_TYPE: drive
      RCLONE_CONFIG_GDRIVE_SCOPE: drive
      RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE: /run/secrets/google_service_account
      RESTIC_CACHE_DIR: /cache
    secrets:
      - google_service_account
    volumes:
      - ./config:/config:ro
      - /apps:/apps:ro
      - /apps/autorestic/cache:/cache
    restart: unless-stopped

secrets:
  google_service_account:
    environment: GOOGLE_SERVICE_ACCOUNT_JSON
