services:
  resticprofile:
    # nosemgrep
    image: creativeprojects/resticprofile:0.33.1@sha256:6d82b4cd23a40f823f71eabf2d83dbfa584efd7b94e6b5258ca0e7b014bc9185
    entrypoint: [sh]
    command: >-
      -c "resticprofile schedule --all && exec crond -f -L /dev/stdout"
    environment:
      TZ: ${TZ:-Etc/UTC}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD:?}
      RESTIC_FROM_PASSWORD: ${RESTIC_PASSWORD:?}
      RESTICPROFILE_LOCK_WAIT: 1h
      RCLONE_CONFIG: /config/rclone/rclone.conf
      RCLONE_CONFIG_GDRIVE_TYPE: drive
      RCLONE_CONFIG_GDRIVE_SCOPE: drive
      RCLONE_CONFIG_GDRIVE_CLIENT_ID: ${GDRIVE_CLIENT_ID:?}
      RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: ${GDRIVE_CLIENT_SECRET:?}
      RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID: ${GDRIVE_FOLDER_ID:?}
      NTFY_TOPIC_PREFIX: ${NTFY_TOPIC_PREFIX:?}
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    uts: host
    volumes:
      - ./config:/resticprofile:ro
      - /apps/rclone:/config/rclone
      - /apps:/apps:ro
      - /backups/restic:/backup
      - /apps/resticprofile/cache:/var/cache/restic
    healthcheck:
      test: [CMD, resticprofile, snapshots]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  rsync:
    image: instrumentisto/rsync-ssh:alpine3.23@sha256:6cbad37c2fbdca4ac7ad9d1c1bb8990af9efd4dc76321b349935876cbb1e9e4a
    profiles:
      - rsync
    tty: false
    command:
      - rsync
      - --archive
      - --hard-links
      - --acls
      - --xattrs
      - --numeric-ids
      - --sparse
      - --partial
      - --one-file-system
      - --delete-after
      - --delete-excluded
      - --exclude-from=/config/exclude.txt
      - /apps/
      - /data/apps/
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./config:/config:ro
      - /apps:/apps:ro
      - /data/apps:/data/apps
    restart: no
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  rclone:
    image: ghcr.io/rclone/rclone:1.74.4@sha256:c61954aaa32328a5486715dd063a81c7879f5195ad3505cd362deddd509dc4a1
    profiles:
      - rclone
    tty: false
    command:
      - sync
      - --track-renames
      - --one-file-system
      - --ignore-case
      - --delete-excluded
      - --exclude-from
      - /config/exclude.txt
      - --exclude-if-present
      - .nobackup
      - --exclude-if-present
      - CACHEDIR.TAG
      - /apps/
      - /data/apps/
    cap_add:
      - DAC_OVERRIDE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./config:/config:ro
      - /apps:/apps:ro
      - /data/apps:/data/apps
    tmpfs:
      - /root
    restart: no
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

networks:
  default:
    name: proxy
    external: true
