# SearXNG user settings
use_default_settings: true

server:
  image_proxy: true

search:
  formats:
    - html
    - json
    - csv
    - rss

engines:
  - name: braveapi
    api_key: "{{ .Env.BRAVE_SEARCH_API_KEY }}"
    inactive: false
