# SearXNG user settings
use_default_settings:
  engines:
    remove:
      - ahmia
      - torch
      - wikidata

search:
  formats:
    - html
    - json
    - csv
    - rss

server:
  image_proxy: true
