# SearXNG user settings
use_default_settings: true

engines:
  - name: braveapi
    api_key: "{{ .Env.BRAVE_SEARCH_API_KEY }}"
    inactive: false

search:
  formats:
    - html
    - json
    - csv
    - rss

server:
  image_proxy: true

outgoing:
  useragent_suffix: "{{ .Env.SEARXNG_USERAGENT_SUFFIX }}"
