services:
  pangolin:
    image: docker.io/fosrl/pangolin:latest
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/pangolin/config:/app/config
    tmpfs:
      - /tmp
    healthcheck:
      test: [CMD, curl, -f, "http://localhost:3001/api/v1/"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2g
          pids: 512

  gerbil:
    image: docker.io/fosrl/gerbil:latest
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    depends_on:
      pangolin:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - /apps/pangolin/config:/var/config
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
      - 443:443
      - 443:443/udp
      - 80:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  traefik:
    image: docker.io/traefik:v3.6
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    depends_on:
      pangolin:
        condition: service_healthy
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/pangolin/traefik:/etc/traefik:ro
      - /apps/pangolin/letsencrypt:/letsencrypt
    network_mode: service:gerbil
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
