services:
  newt:
    # nosemgrep
    image: ghcr.io/fosrl/newt:1.15.0@sha256:d69d047c816ca7721eae90d5f3cd3be53b615b3d498678be21488d666538ee5c
    command: ["-prefer-endpoint=gerbil:51820"]
    environment:
      DOCKER_SOCKET: tcp://socket-proxy:2375
      NEWT_ID: ${NEWT_ID:?}
      NEWT_SECRET: ${NEWT_SECRET:?}
      PANGOLIN_ENDPOINT: ${PANGOLIN_ENDPOINT:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/pangolin/newt:/root/.config/newt-client
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - default
      - socket-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

networks:
  default:
    name: proxy
    external: true
  socket-proxy:
    name: socket-proxy
    external: true
