api:
  insecure: true
  dashboard: true

providers:
  http:
    endpoint: http://pangolin:3001/api/v1/traefik-config
  file:
    directory: /etc/traefik/dynamic

experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.4.1
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.6.0

log:
  level: INFO
  format: json

accessLog:
  format: json

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: duckdns
      storage: /letsencrypt/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 30m
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: letsencrypt
      middlewares:
        - crowdsec@file
        - badger@file
        - security-headers@file
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedQuestionMark: true

serversTransport:
  insecureSkipVerify: true

ping:
  entryPoint: web
