services:
  arcane:
    # nosemgrep
    image: ghcr.io/getarcaneapp/manager:v2.5.0@sha256:287d3c096b1362838b1fa04767fb1d981a6aab322c2f866281451c898a3f96f6
    environment:
      APP_URL: ${APP_URL:-http://localhost:3552}
      PUID: ${PUID:-}
      PGID: ${PGID:-}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:?}
      JWT_SECRET: ${JWT_SECRET:?}
      LOG_JSON: true
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/arcane/data:/app/data
      - /apps/arcane/cache:/builds
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /tmp
    ports:
      - 3552:3552
    healthcheck:
      test: [CMD, /app/arcane, health]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth arcane arcane:3552

networks:
  default:
    name: proxy
    external: true
