services:
  crowdsec:
    # nosemgrep
    image: ghcr.io/crowdsecurity/crowdsec:v1.7.8@sha256:2f527c9bb8b367120eb08b82890aa912ce96bfa1ada93dda0721700e4b4e0dde
    environment:
      COLLECTIONS: >-
        crowdsecurity/appsec-crs
        crowdsecurity/appsec-crs-inband
        crowdsecurity/appsec-generic-rules
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/caddy
        crowdsecurity/iptables
        crowdsecurity/linux-lpe
      DOCKER_HOST: tcp://socket_proxy:2375
      TZ: ${TZ:-UTC}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    uts: host
    volumes:
      - /apps/crowdsec/config:/etc/crowdsec
      - /apps/crowdsec/data:/var/lib/crowdsec/data
      - ./acquis.d:/etc/crowdsec/acquis.d:ro
      - /var/log:/var/log:ro
    tmpfs:
      - /tmp
    expose:
      - 8080
      - 7422
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - default
      - socket_proxy
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:8080/health"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  crowdsec-firewall-bouncer:
    # nosemgrep
    image: ghcr.io/shgew/cs-firewall-bouncer-docker:v0.0.34-patch1@sha256:c33bae81fdade1e1c243946bedfcdb5b22a25c4fbd1ef166ce32935334d7575c
    # Optional non-root mode:
    # user: 1000:1000
    depends_on:
      crowdsec:
        condition: service_healthy
    environment:
      API_URL: http://localhost:8080
      API_KEY: ${CROWDSEC_FIREWALL_BOUNCER_KEY:-}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt: # In non-root mode, remove this block.
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./crowdsec-firewall-bouncer.yaml:/config/crowdsec-firewall-bouncer.yaml:ro
    tmpfs:
      - /tmp
    network_mode: host
    healthcheck:
      test: [CMD, pidof, crowdsec-firewall-bouncer]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

networks:
  default:
    name: caddy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true
