services:
  gomplate:
    image: ghcr.io/hairyhenderson/gomplate:latest@sha256:caf942c5bbcb2cdcd15230e93e138825ecbcc0e590afab85d37a1c2b5c7b3523
    command:
      - --file=/input/notifications.template.yml
      - --out=/output/notifications.yml
    environment:
      NTFY_TOPIC_PREFIX: ${NTFY_TOPIC_PREFIX:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./dozzle:/input:ro
      - /apps/dozzle:/output
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
          pids: 512

  dozzle:
    # nosemgrep
    image: ghcr.io/amir20/dozzle:v10.7.2@sha256:01f9018ffdaa0ec523f9a91dea3eff65b25cdb5f0566ac6d5a2cb4cf591e35e9
    depends_on:
      gomplate:
        condition: service_completed_successfully
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      DOZZLE_ENABLE_ACTIONS: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/dozzle:/data
    expose:
      - 8080
    networks:
      - default
      - socket-proxy
    healthcheck:
      test: [CMD, /dozzle, healthcheck]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth dozzle dozzle:8080

  beszel:
    # nosemgrep
    image: ghcr.io/henrygd/beszel/beszel:0.18.8@sha256:d562169ffe44b294ec847d2129a11621b5086aa62128ec37352ab4a194256103
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/beszel/hub:/beszel_data
    tmpfs:
      - /tmp
    ports:
      - 127.0.0.1:8090:8090
    healthcheck:
      test: [CMD, /beszel, health, --url, "http://localhost:8090"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth beszel beszel:8090

  beszel-agent:
    # nosemgrep
    image: ghcr.io/henrygd/beszel/beszel-agent:0.18.8@sha256:f8f493cc228efeccedded61b4f67d81f3d9cbde7d7174d7732382fab6c03dac2
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      HUB_URL: ${HUB_URL:-http://localhost:8090}
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      DOCKER_HOST: ${DOCKER_HOST:-tcp://localhost:2375}
    volumes:
      - /apps/beszel/agent:/var/lib/beszel-agent
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    network_mode: host
    healthcheck:
      test: [CMD, /agent, health]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

networks:
  default:
    name: proxy
    external: true
  socket-proxy:
    name: socket-proxy
    external: true
