services:
  gomplate:
    image: ghcr.io/hairyhenderson/gomplate:latest@sha256:e5428fefe892fe30eddbf15bbf9f5d37093d268d139155fc1879a00a42b9a895
    command:
      - --file=/input/notifications.template.yml
      - --out=/output/notifications.yml
    environment:
      NTFY_TOPIC_PREFIX: ${NTFY_TOPIC_PREFIX:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./dozzle:/input:ro
      - /apps/dozzle:/output
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
          pids: 512

  dozzle:
    # nosemgrep
    image: ghcr.io/amir20/dozzle:v11.3.0@sha256:a7d69d20891d3dcc82636e24afa4c1c162b41d0673ef798b14f09e6b69accc5a
    depends_on:
      gomplate:
        condition: service_completed_successfully
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      DOZZLE_ENABLE_ACTIONS: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/dozzle:/data
    expose:
      - 8080
    networks:
      - default
      - socket-proxy
    healthcheck:
      test: [CMD, /dozzle, healthcheck]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth dozzle dozzle:8080

  beszel:
    # nosemgrep
    image: ghcr.io/henrygd/beszel/beszel:0.21.0@sha256:020d80f5974e66356e6d6440736952edc9b9ea59978ac9f98418b5fb643dc0e2
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/beszel/hub:/beszel_data
    tmpfs:
      - /tmp
    ports:
      - 127.0.0.1:8090:8090
    healthcheck:
      test: [CMD, /beszel, health, --url, "http://localhost:8090"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth beszel beszel:8090

  beszel-agent:
    # nosemgrep
    image: ghcr.io/henrygd/beszel/beszel-agent:0.21.0@sha256:a197364e01b97dc1d5931679a1d4d71e3c63045f5835b1d77b420d5c545cc46d
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      HUB_URL: ${HUB_URL:-http://localhost:8090}
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      DOCKER_HOST: ${DOCKER_HOST:-tcp://localhost:2375}
    volumes:
      - /apps/beszel/agent:/var/lib/beszel-agent
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    network_mode: host
    healthcheck:
      test: [CMD, /agent, health]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

networks:
  default:
    name: proxy
    external: true
  socket-proxy:
    name: socket-proxy
    external: true
