services:
  homeassistant:
    # nosemgrep
    image: ghcr.io/home-assistant/home-assistant:2026.6.3@sha256:aed891b8f801072302815b4b0fab5adb714182967e9d2e2d4a2be558241c73ad
    healthcheck:
      test: [CMD, curl, -fSs, "http://localhost:8123"]
    environment:
      TZ: ${TZ:-UTC}
    # privileged: true
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /apps/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy homeassistant ${IP_ADDRESS:?}:8123

  music_assistant:
    # nosemgrep
    image: ghcr.io/music-assistant/server:2.9.1@sha256:d2fc378b591c83943025df64d7d5bfa722075f02a67e71fc157bed893a5fed6e
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - /apps/music_assistant:/data
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy music_assistant ${IP_ADDRESS:?}:8095

  esphome:
    # nosemgrep
    image: ghcr.io/esphome/esphome:2026.5.3@sha256:c1a2a042e351ed07d7e8e703f3b51dec9f836921cdfc867a5fd5472bad36b9fb
    healthcheck:
      test: [CMD, curl, -fSs, "http://localhost:6052"]
    environment:
      TZ: ${TZ:-UTC}
    # privileged: true
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /apps/esphome:/config
    network_mode: host
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy esphome ${IP_ADDRESS:?}:6052

  trmnl_ha:
    # nosemgrep
    image: ghcr.io/usetrmnl/trmnl-ha-${ARCH:-amd64}:0.8.1
    healthcheck:
      test: [CMD, curl, -fSs, "http://localhost:10000/health"]
    environment:
      HOME_ASSISTANT_URL: http://${IP_ADDRESS:?}:8123
      ACCESS_TOKEN: ${HOME_ASSISTANT_TOKEN}
      KEEP_BROWSER_OPEN: "true"
      TZ: ${TZ:-UTC}
    volumes:
      - /apps/trmnl-ha:/data
    ports:
      - 10000:10000
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy trmnl_ha trmnl_ha:10000

networks:
  default:
    name: caddy
    external: true
