services:
  caddy:
    # nosemgrep
    image: ghcr.io/serfriz/caddy-duckdns-ddns-crowdsec-geoip-security-dockerproxy:2.11.4@sha256:d2486aeb3524ceb8412910c86f2f3e5f42fff2cbbfb9857f935a4006326e50b7
    healthcheck:
      test: [CMD, wget, -qO, /dev/null, "http://127.0.0.1:2019/config/"]
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /srv/Caddyfile
      DOCKER_HOST: tcp://socket_proxy:2375
      DOMAIN: ${DOMAIN:?}
    secrets:
      - duckdns_token
    volumes:
      - ./caddy:/srv:ro
      - /apps/caddy:/data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - default
      - socket_proxy
    depends_on:
      socket_proxy:
        condition: service_healthy
    restart: unless-stopped

  duckdns:
    # nosemgrep
    image: lscr.io/linuxserver/duckdns:version-d67e71cc@sha256:424dbc5a5db5388ad4c197882eac475c5bfad2be1e02a761692946d406591b17
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS:?}
      - FILE__TOKEN=/run/secrets/duckdns_token
    secrets:
      - duckdns_token
    restart: unless-stopped

  tinyauth:
    # nosemgrep
    image: ghcr.io/steveiliop56/tinyauth:v5.0.7@sha256:0793c71c49906e079d90c7e693cded9df569217a92d717dc9b171f2116fcd1c6
    environment:
      DOCKER_HOST: tcp://socket_proxy:2375
      TINYAUTH_APPURL: https://tinyauth.${DOMAIN:?}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRETFILE: /run/secrets/github_oauth_client_secret
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRETFILE: /run/secrets/google_oauth_client_secret
      TINYAUTH_OAUTH_WHITELIST: ${TINYAUTH_OAUTH_WHITELIST:?}
    secrets:
      - github_oauth_client_secret
      - google_oauth_client_secret
    volumes:
      - /apps/tinyauth:/data
    expose:
      - 3000
    networks:
      - default
      - socket_proxy
    depends_on:
      socket_proxy:
        condition: service_healthy
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy tinyauth tinyauth:3000

  socket_proxy:
    # nosemgrep
    image: ghcr.io/linuxserver/socket-proxy:3.2.19@sha256:de8215f99a9ce4bbff5d8853d7a5ae4bbe6baa0ed868046a0251320a4fb05aa2
    environment:
      TZ: ${TZ:-UTC}
      POST: 0

      # containers
      CONTAINERS: 1
      EXEC: 0
      # post only
      ALLOW_START: 1 # dozzle
      ALLOW_STOP: 1 # dozzle
      ALLOW_RESTARTS: 1 # autoheal

      # images
      IMAGES: 0
      # post only
      BUILD: 0
      COMMIT: 0

      # networks / volumes / plugins
      NETWORKS: 1 # caddy
      VOLUMES: 0
      PLUGINS: 0

      # swarm
      CONFIGS: 1 # caddy
      NODES: 0
      SECRETS: 0
      SERVICES: 1 # caddy
      SWARM: 0
      TASKS: 0

      # system
      # get only
      DISTRIBUTION: 0
      EVENTS: 1
      INFO: 1 # caddy
      PING: 1
      SYSTEM: 0
      VERSION: 1
      # post only
      AUTH: 0
      SESSION: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    expose:
      - 2375
    networks:
      - socket_proxy
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:2375/_ping"]
    restart: unless-stopped
    read_only: true

  tailscale:
    # nosemgrep
    image: ghcr.io/tailscale/tailscale:v1.98.4
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?}
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TS_ROUTES:-}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_ENABLE_HEALTH_CHECK: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /apps/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    uts: host
    healthcheck:
      test: [CMD, wget, -nv, -O-, "http://localhost:9002/healthz"]
    restart: unless-stopped

  whoami:
    # nosemgrep
    image: ghcr.io/traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    expose:
      - 80
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth whoami whoami:80

  librespeed:
    # nosemgrep
    image: ghcr.io/librespeed/speedtest:6.1.0@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
    expose:
      - 8080
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth librespeed librespeed:8080

networks:
  socket_proxy:
    name: socket_proxy

secrets:
  duckdns_token:
    environment: DUCKDNS_TOKEN
  github_oauth_client_secret:
    environment: TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET
  google_oauth_client_secret:
    environment: TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET
