services:
  caddy:
    image: ghcr.io/serfriz/caddy-duckdns-ddns-crowdsec-geoip-security-dockerproxy:2.11.3
    healthcheck:
      test: [CMD, wget, -qO, /dev/null, "http://127.0.0.1:2019/config"]
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      CADDY_DOCKER_CADDYFILE_PATH: /srv/Caddyfile
    secrets:
      - duckdns_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy:/srv
      - /data/caddy:/data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:version-d67e71cc
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - FILE__TOKEN=/run/secrets/duckdns_token
    secrets:
      - duckdns_token
    restart: unless-stopped

  whoami:
    image: ghcr.io/traefik/whoami:v1.11.0
    expose:
      - 80
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy whoami whoami:80

  httpbin:
    image: ghcr.io/mccutchen/go-httpbin:2.21.0
    expose:
      - 8080
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy httpbin httpbin:8080

  librespeed:
    image: ghcr.io/librespeed/speedtest:6.1.0
    expose:
      - 8080
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy librespeed librespeed:8080

secrets:
  duckdns_token:
    environment: DUCKDNS_TOKEN
