services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - FILE__TOKEN=/run/secrets/duckdns_token
    secrets:
      - duckdns_token
    restart: unless-stopped

  whoami:
    image: ghcr.io/traefik/whoami:latest
    expose:
      - 80
    restart: unless-stopped

  httpbin:
    image: ghcr.io/mccutchen/go-httpbin:latest
    expose:
      - 8080
    restart: unless-stopped

  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    expose:
      - 8080
    restart: unless-stopped

secrets:
  duckdns_token:
    environment: DUCKDNS_TOKEN
