services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_ONLY_MONITOR_RUNNING: true
      DOCKER_HOST: tcp://socket_proxy:2375
      WEBHOOK_URL: https://ntfy.sh/${NTFY_TOPIC_PREFIX:?}-autoheal
    depends_on:
      socket_proxy:
        condition: service_healthy
    restart: unless-stopped

  dozzle:
    image: ghcr.io/amir20/dozzle:v10.6.5
    environment:
      DOCKER_HOST: tcp://socket_proxy:2375
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_AUTH_PROVIDER: forward-proxy
    volumes:
      - /apps/dozzle:/data
    expose:
      - 8080
    depends_on:
      socket_proxy:
        condition: service_healthy
    healthcheck:
      test: [CMD, /dozzle, healthcheck]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth dozzle dozzle:8080

  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.18.7
    volumes:
      - /apps/beszel/hub:/beszel_data
    ports:
      - 127.0.0.1:8090:8090
    healthcheck:
      test: [CMD, /beszel, health, --url, "http://localhost:8090"]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth beszel beszel:8090

  beszel_agent:
    image: ghcr.io/henrygd/beszel/beszel-agent:0.18.7
    environment:
      HUB_URL: http://localhost:8090
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
    volumes:
      - /apps/beszel/agent:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    network_mode: host
    healthcheck:
      test: [CMD, /agent, health]
    restart: unless-stopped

  socket_proxy:
    image: ghcr.io/linuxserver/socket-proxy:latest
    environment:
      TZ: ${TZ:-UTC}
      POST: 0

      # containers
      CONTAINERS: 1
      EXEC: 0
      # post only
      ALLOW_START: 1 # dozzle
      ALLOW_STOP: 1 # dozzle
      ALLOW_RESTARTS: 1 # autoheal

      # images
      IMAGES: 0
      # post only
      BUILD: 0
      COMMIT: 0

      # networks / volumes / plugins
      NETWORKS: 1 # caddy
      VOLUMES: 0
      PLUGINS: 0

      # swarm
      CONFIGS: 1 # caddy
      NODES: 0
      SECRETS: 0
      SERVICES: 1 # caddy
      SWARM: 0
      TASKS: 0

      # system
      # get only
      DISTRIBUTION: 0
      EVENTS: 1
      INFO: 1 # caddy
      PING: 1
      SYSTEM: 0
      VERSION: 1
      # post only
      AUTH: 0
      SESSION: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:2375/_ping"]
    restart: unless-stopped
    read_only: true

networks:
  default:
    name: public_default
    external: true
