services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_ONLY_MONITOR_RUNNING: true
      WEBHOOK_URL: https://ntfy.sh/${NTFY_TOPIC_PREFIX:?}-autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.18.7
    volumes:
      - /data/beszel:/beszel_data
    expose:
      - 8090
    healthcheck:
      test: [CMD, /beszel, health, --url, "http://localhost:8090"]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy beszel beszel:8090

  # dozzle:
  #   image: ghcr.io/amir20/dozzle:v10.6.3
  #   environment:
  #     DOZZLE_ENABLE_ACTIONS: true
  #     DOZZLE_ENABLE_SHELL: true
  #   volumes:
  #     - /data/dozzle:/data
  #   expose:
  #     - 8080
  #   healthcheck:
  #     test: [CMD, /dozzle, healthcheck]
  #   restart: unless-stopped
  #   labels:
  #     caddy: "*.{$$DOMAIN}"
  #     caddy.import: reverse_proxy dozzle dozzle:8080

networks:
  default:
    name: public_default
    external: true
