http:
  middlewares:
    badger:
      plugin:
        badger:
          disableForwardAuth: true
    default-whitelist:
      ipAllowList:
        sourceRange:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - 100.89.137.0/20
    security-headers:
      headers:
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Forwarded-Proto: https
        sslProxyHeaders:
          X-Forwarded-Proto: https
        hostsProxyHeaders:
          - X-Forwarded-Host
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: strict-origin-when-cross-origin
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    crowdsec:
      plugin:
        crowdsec:
          enabled: true
          CrowdsecMode: stream
          crowdsecAppsecEnabled: true
          crowdsecLapiKey: '{{env "CROWDSEC_TRAEFIK_BOUNCER_KEY"}}'
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.89.137.0/20
          forwardedHeadersTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.89.137.0/20

  routers:
    next-router:
      rule: Host(`{{env "PANGOLIN_DOMAIN"}}`) && !PathPrefix(`/api/v1`)
      service: next-service
      entryPoints:
        - websecure

    api-router:
      rule: Host(`{{env "PANGOLIN_DOMAIN"}}`) && PathPrefix(`/api/v1`)
      service: api-service
      entryPoints:
        - websecure

  services:
    next-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3002

    api-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3000

tcp:
  serversTransports:
    pp-transport-v1:
      proxyProtocol:
        version: 1
    pp-transport-v2:
      proxyProtocol:
        version: 2
