http:
  middlewares:
    badger:
      plugin:
        badger:
          disableForwardAuth: true
    security-headers:
      headers:
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Forwarded-Proto: https
          Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' wss: ws:; frame-ancestors 'self'; form-action 'self'; object-src 'none'; base-uri 'self'; upgrade-insecure-requests"
          Cross-Origin-Opener-Policy: same-origin
          Cross-Origin-Resource-Policy: same-site
          Permissions-Policy: "camera=(self), microphone=(self), geolocation=(self), payment=(self), usb=(self), serial=(self), hid=(self), midi=(self), display-capture=(self), bluetooth=(self), idle-detection=(), accelerometer=(), gyroscope=(), magnetometer=(), xr-spatial-tracking=()"
          Referrer-Policy: strict-origin-when-cross-origin
          X-DNS-Prefetch-Control: "off"
          X-Permitted-Cross-Domain-Policies: none
          X-Robots-Tag: noindex, nofollow
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
    crowdsec:
      plugin:
        crowdsec:
          enabled: true
          CrowdsecMode: stream
          crowdsecAppsecEnabled: true
          crowdsecLapiKey: '{{env "CROWDSEC_TRAEFIK_BOUNCER_KEY"}}'
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.89.137.0/20
          forwardedHeadersTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.89.137.0/20

  routers:
    next-router:
      rule: Host(`{{env "PANGOLIN_DOMAIN"}}`) && !PathPrefix(`/api/v1`)
      service: next-service
      entryPoints:
        - websecure

    api-router:
      rule: Host(`{{env "PANGOLIN_DOMAIN"}}`) && PathPrefix(`/api/v1`)
      service: api-service
      entryPoints:
        - websecure

  services:
    next-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3002

    api-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3000

tcp:
  serversTransports:
    pp-transport-v1:
      proxyProtocol:
        version: 1
    pp-transport-v2:
      proxyProtocol:
        version: 2
