services:
  immich_server:
    # nosemgrep
    image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ${UPLOAD_LOCATION:?}:/data
      - ${LIBRARY_LOCATION:?}:/data/library
    expose:
      - 2283
    networks:
      - default
      - caddy
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    healthcheck:
      test: [CMD, bash, -c, ":> /dev/tcp/localhost/2283"]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy immich immich_server:2283

  immich_machine_learning:
    # nosemgrep
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3
    # extends:
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference
    volumes:
      - /apps/immich/model/cache:/cache
    networks:
      default:
        aliases:
          - immich-machine-learning
    healthcheck:
      test: [CMD, bash, -c, ":> /dev/tcp/localhost/3003"]
    restart: unless-stopped

  redis:
    # nosemgrep
    image: ghcr.io/valkey-io/valkey:9.1.0@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    healthcheck:
      test: [CMD, valkey-cli, ping]
    restart: unless-stopped

  database:
    # nosemgrep
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3@sha256:65538806314b93e2a8efea4acd78d2b348606eb2bd921b1494ce5b241f6ffbdf
    # user: ${PUID:-1000}:${PGID:-1000}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGUSER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-immich}
      PGDATABASE: ${POSTGRES_DB:-immich}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION:?}:/var/lib/postgresql
      - /etc/passwd:/etc/passwd:ro
    shm_size: 128mb
    healthcheck:
      test: [CMD, pg_isready]
    restart: unless-stopped

  gphotos2immich:
    # nosemgrep
    image: ghcr.io/warreth/gphotos2immich:v1.6.1@sha256:cf748ba1c1ddfe291bb03ba101c0c44a426ee1a6d66133420a2db18130714529
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:8080/"]
    environment:
      PORT: "8080"
      DISABLE_WEBUI: "false"
    volumes:
      - /apps/gphotos2immich/config.json:/app/config.json
      - /apps/gphotos2immich/data:/app/data
    expose:
      - 8080
    networks:
      - caddy
    depends_on:
      immich_server:
        condition: service_healthy
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy gphotos2immich gphotos2immich:8080

  immich_kiosk:
    # nosemgrep
    image: ghcr.io/damongolding/immich-kiosk:0.39.3@sha256:b65371b9fbe93cde8355c06ba095fb4801bbb5d7c8c51065a5bfa02183536771
    tty: true
    # healthcheck:
    #   test: [CMD, curl, -fsS, "http://localhost:3000/health"]
    environment:
      LANG: en_US
      TZ: ${TZ:-UTC}
    volumes:
      - /apps/immich_kiosk:/config
    expose:
      - 3000
    networks:
      - caddy
    depends_on:
      immich_server:
        condition: service_healthy
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy immich_kiosk immich_kiosk:3000

networks:
  default:
  caddy:
    name: caddy
    external: true
