version: 2

global:
  forget:
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 3
    prune: true

backends:
  gdrive:
    type: rclone
    path: gdrive:backups/apps
    requireKey: true

locations:
  apps:
    from: /apps
    to: gdrive
    cron: "@daily"
    options:
      backup:
        iexclude:
          - "**/cache"
          - "**/MediaCover"
          - profilarr/data/databases
          - prowlarr/Definitions
