version: "3.8"

services:
  whoami:
    image: traefik/whoami
    networks:
      - dokploy-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.whoami.rule=Host("${DOMAIN}")'
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
