services:
  caddy:
    # nosemgrep
    image: ghcr.io/serfriz/caddy-duckdns-ddns-crowdsec-geoip-security-dockerproxy:2.11.4@sha256:0f860e623b91d11bf3a75a1a82462a714f181ea6b5db4ebfaae0babeda2c6633
    container_name: caddy
    working_dir: /etc/caddy
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile
      CADDY_DOCKER_EVENT_THROTTLE_INTERVAL: 2s # for crowdset stream mode
      CROWDSEC_API_KEY: ${CROWDSEC_CADDY_BOUNCER_KEY:-}
      DOCKER_HOST: tcp://socket-proxy:2375
      DOMAIN: ${DOMAIN:?}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN:?}
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./caddy:/etc/caddy:ro
      - /apps/caddy:/config
      - /apps/caddy:/data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - default
      - socket-proxy
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost/healthz"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512

  tinyauth:
    # nosemgrep
    image: ghcr.io/tinyauthapp/tinyauth:v5.0.7@sha256:0793c71c49906e079d90c7e693cded9df569217a92d717dc9b171f2116fcd1c6
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      TINYAUTH_APPURL: https://tinyauth.${DOMAIN:?}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ${TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET:-}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID:-}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET: ${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET:-}
      TINYAUTH_OAUTH_WHITELIST: ${TINYAUTH_OAUTH_WHITELIST:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/tinyauth:/data
    expose:
      - 3000
    networks:
      - default
      - socket-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy tinyauth tinyauth:3000

networks:
  default:
    name: proxy
    external: true
  socket-proxy:
    name: socket-proxy
    external: true
