services:
  portainer:
    image: portainer/portainer-ce:lts
    command: --data ${PORTAINER_DATA}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - PORTAINER_DATA=${PORTAINER_DATA:?}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA}:/data
      - ${PORTAINER_DATA}:${PORTAINER_DATA}
    ports:
      - 9443:9443
    expose:
      - 8000
      - 9000
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9000/api/status"]
    restart: unless-stopped
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy portainer portainer:9000

networks:
  default:
    name: public_default
    external: true
