all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_user: "{{ default_user }}"
          ansible_become: true
    lxc:
      hosts:
        docker-lxc:
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_host: "{{ pve_api_host }}"
          ansible_user: "{{ default_user }}"
          ansible_proxmox_sudo: true
          proxmox_vmid: "{{ lxc_vmid }}"
    oci:
      hosts:
        oci-vps:
          ansible_user: "{{ default_user }}"
          ansible_become: true
