- name: Create LXC container on Proxmox
  hosts: proxmox
  gather_facts: false
  roles:
    - lxc

- name: Configure LXC
  hosts: lxc
  become: true
  pre_tasks:
    - name: Wait for container to be ready
      ansible.builtin.wait_for_connection:
        timeout: 60
  roles:
    - robertdebock.update
    - init
    - geerlingguy.security
    - geerlingguy.docker
