- name: Create LXC container on Proxmox
  hosts: proxmox
  roles:
    - lxc

- name: Configure LXC
  hosts: lxc
  become: true
  gather_facts: false
  roles:
    - robertdebock.bootstrap
    - robertdebock.update
    - bootstrap
    - geerlingguy.security
    - geerlingguy.docker
