- name: Create LXC container on Proxmox
  hosts: proxmox
  gather_facts: false
  roles:
    - lxc

- name: Configure LXC
  hosts: lxc
  become: true
  roles:
    - robertdebock.update
    - init
    - geerlingguy.security
    - geerlingguy.docker
