- name: Configure OCI VPS
  hosts: oci
  become: true
  roles:
    - robertdebock.bootstrap
    - robertdebock.update
    - bootstrap
    - oci_firewall
    - geerlingguy.security
    - geerlingguy.docker
