collections:
  - name: community.general
    version: ">=9.0.0"
  - name: ansible.posix
    version: ">=1.6.0"

roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.update
  - name: lae.proxmox
  - name: geerlingguy.security
  - name: geerlingguy.docker
