services:
  sencho:
    image: ghcr.io/studio-saelix/sencho:0.92.0@sha256:dfc60ca163c0de68f3a17d3720a7b929456e491b2cec7af8b3500f44a19795c2
    environment:
      COMPOSE_DIR: ${COMPOSE_DIR:?}
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /apps/sencho:/app/data
      - ${COMPOSE_DIR:-${HOME}}:${COMPOSE_DIR:-${HOME}}
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /tmp
    ports:
      - 1852:1852
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth sencho sencho:1852
      tinyauth.apps.sencho.path.allow: \/pilot

networks:
  default:
    name: caddy
    external: true
