services:
  dockhand:
    # nosemgrep
    image: fnsys/dockhand:v1.0.36@sha256:ca0aa45aa61f35b521e05a7bbf79dcd571660e2a516dec49cca6fe374251abcc
    environment:
      DATA_DIR: ${DOCKHAND_DATA:?}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ../:/home/dockhand/
      - ${DOCKHAND_DATA}:${DOCKHAND_DATA}
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    # network_mode: host  # required for initial setup
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          pids: 512
    labels:
      caddy: "*.{$$DOMAIN}"
      caddy.import: reverse_proxy_auth dockhand dockhand:3000

networks:
  default:
    name: caddy
    external: true
