services:
  dockhand:
    # nosemgrep
    image: fnsys/dockhand:v1.0.33
    ports:
      - 3000:3000
    volumes:
      - /apps/dockhand:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # network_mode: host  # required for initial setup
    restart: unless-stopped

networks:
  default:
    name: caddy
    external: true
