# To see all available options, please visit the docs:
# https://docs.pangolin.net/

gerbil:
  start_port: 51820
  base_endpoint: "{{ .Env.PANGOLIN_DOMAIN }}"
  # Optional network settings (defaults shown):
  # subnet_group: "100.89.137.0/20"
  # block_size: 24
  # site_block_size: 30

app:
  dashboard_url: https://{{ .Env.PANGOLIN_DOMAIN }}
  log_level: info
  telemetry:
    anonymous_usage: true

domains:
  main:
    base_domain: "{{ .Env.DOMAIN }}"

server:
  cors:
    origins: ["https://{{ .Env.PANGOLIN_DOMAIN }}"]
    methods: [GET, POST, PUT, DELETE, PATCH]
    allowed_headers: [X-CSRF-Token, Content-Type]
    credentials: false
  maxmind_db_path: /usr/share/GeoIP/GeoLite2-Country.mmdb
  maxmind_asn_path: /usr/share/GeoIP/GeoLite2-ASN.mmdb

# Optional organization network settings (defaults shown):
# orgs:
#     block_size: 24
#     subnet_group: "100.90.128.0/20"
#     utility_subnet_group: "100.96.128.0/20"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: false
  allow_raw_resources: true
