name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  lint-title:
    permissions:
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387335d99d94262e6da274be960bb17ad8bc # v5.5.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0

  label-size:
    permissions:
      contents: read
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@646f890e17621c1704e17926715f430541793774 # v0.5.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          IGNORED: |
            package-lock.json
            *.lock
            docs/**
